# This is a configuration file for the bacon tool
# More info at https://github.com/Canop/bacon

default_job = "check-all"

[jobs]

[jobs.check]
command = ["cargo", "check", "--color", "always"]
need_stdout = false

[jobs.check-all]
command = [
	"cargo", "check",
	"--all-targets",
	"--features", "crossterm",
	"--color", "always",
]
need_stdout = false
watch = ["tests", "benches", "examples"]

[jobs.ex]
command = [
	"cargo", "run",
	"--color", "always",
	"--features", "crossterm",
	"--example"
]
allow_warnings = true
need_stdout = true

[jobs.clippy-all]
command = [
	"cargo", "clippy",
	"--color", "always",
	"--",
	"-A", "clippy::match_like_matches_macro",
	"-A", "clippy::collapsible_if",
	"-A", "clippy::collapsible_else_if",
	"-A", "clippy::manual_range_contains",
	"-A", "clippy::collapsible_else_if",
]
need_stdout = false

[jobs.test]
command = ["cargo", "test", "--color", "always", "--features", "crossterm"]
need_stdout = true
watch = ["tests"]

[jobs.doc]
command = ["cargo", "doc", "--color", "always", "--no-deps"]
need_stdout = false
