[package]
name = "coolor"
version = "0.1.0"
edition = "2018"
authors = ["dystroy <denys.seguret@gmail.com>"]
repository = "https://github.com/Canop/coolor"
description = "conversion between color formats"
keywords = ["terminal", "ansi", "hsl", "rgb", "color"]
license = "MIT"
readme = "README.md"

[dependencies]
ansi_colours = "1.0"
thiserror = "1.0"

[dev-dependencies]
crossterm = "0.21"
