[package]
name = "coolor"
version = "0.5.0"
edition = "2021"
authors = ["dystroy <denys.seguret@gmail.com>"]
repository = "https://github.com/Canop/coolor"
description = "conversion between color formats"
keywords = ["ansi", "hsl", "rgb", "color", "no-std"]
categories = ["no-std"]
license = "MIT"
readme = "README.md"

[features]
default = []

[dependencies]
crossterm = { optional=true, version=">=0.23.2" }

[dev-dependencies]
crossterm = ">=0.23.2"
rand = "0.8"
